services:
  postgres:
    image: postgres:16-alpine
    container_name: easywms-postgres
    environment:
      POSTGRES_DB: easywms
      POSTGRES_USER: easywms
      POSTGRES_PASSWORD: easywms123
    ports:
      - "5432:5432"
    volumes:
      - easywms_pg:/var/lib/postgresql/data

volumes:
  easywms_pg:
