const $=id=>document.getElementById(id);let token=localStorage.getItem('easywms_token')||'';let me=JSON.parse(localStorage.getItem('easywms_user')||'null');let activeMaster='products',scanTarget='',scanStream=null,scanTimer=null;
const titles={dashboard:['Dashboard','ภาพรวมคลังสินค้าแบบ Real-time'],master:['Master Data','ข้อมูลหลักของคลังสินค้า'],inventory:['Inventory','Stock แยกตาม Location'],lots:['Lot / Batch / Expiry','ติดตาม Stock ตาม Lot และวันหมดอายุ'],receive:['Receive','รับสินค้าเข้าคลัง'],issue:['Issue','เบิกสินค้าออก'],transfer:['Stock Transfer','ย้ายสินค้าระหว่าง Location'],stockcount:['Stock Count','ตรวจนับและสร้าง Adjustment Request'],adjustment:['Adjustment Approval','อนุมัติ/ปฏิเสธการปรับ Stock'],movements:['Movements','Audit Trail ของ Stock']};
const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));const fmt=v=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:2});const dateFmt=v=>v?new Date(v).toLocaleString():'-';const dFmt=v=>v?new Date(v).toLocaleDateString():'-';
async function api(url,opt={}){opt.headers={...(opt.headers||{}),Authorization:'Bearer '+token};if(opt.body&&!opt.headers['Content-Type']&&!(opt.body instanceof FormData))opt.headers['Content-Type']='application/json';const r=await fetch(url,opt);if(r.status===401){logout();throw new Error('session expired')}const ct=r.headers.get('content-type')||'';const d=ct.includes('application/json')?await r.json():await r.blob();if(!r.ok)throw new Error(d.error||'request failed');return d}
async function login(){try{const r=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('loginUser').value,password:$('loginPass').value})});const d=await r.json();if(!r.ok)throw new Error(d.error);token=d.token;me=d.user;localStorage.setItem('easywms_token',token);localStorage.setItem('easywms_user',JSON.stringify(me));showApp();loadDashboard()}catch(e){$('loginMsg').textContent=e.message;$('loginMsg').className='msg error'}}function logout(){token='';me=null;localStorage.removeItem('easywms_token');localStorage.removeItem('easywms_user');$('appView').classList.add('hidden');$('loginView').classList.remove('hidden')}
function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('currentUser').textContent=`${me.name} • ${me.role}`;document.querySelectorAll('.admin-only').forEach(x=>x.style.display=me.role==='ADMIN'?'':'none');loadLocations()}
async function loadLocations(){try{const [locations,inventory]=await Promise.all([api('/api/locations'),api('/api/inventory')]);const occupied=new Set(inventory.filter(x=>Number(x.qty)>0).map(x=>x.location?.code));['rLoc','iLoc','tFrom','tTo','cLoc','aLoc'].forEach(id=>{const field=$(id);if(!field)return;const selected=field.value||'A-01-01';const availableForPut=['rLoc','tTo'].includes(id);const options=locations.filter(x=>!availableForPut||!occupied.has(x.code));const select=document.createElement('select');select.id=id;select.innerHTML='<option value="">Select location</option>'+options.map(x=>`<option value="${esc(x.code)}">${esc(x.code)} - ${esc(x.name||'')} (${esc(x.warehouse_code||'-')}/${esc(x.zone_code||'-')})</option>`).join('');select.value=options.some(x=>x.code===selected)?selected:'';field.replaceWith(select)})}catch(e){console.error('Unable to load locations',e)}}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(b.dataset.page).classList.add('active');const [a,c]=titles[b.dataset.page];$('pageTitle').textContent=a;$('pageSub').textContent=c;if(b.dataset.page==='master')loadMaster();if(b.dataset.page==='inventory')loadInventory();if(b.dataset.page==='lots')loadLots();if(b.dataset.page==='stockcount')loadStockCounts();if(b.dataset.page==='adjustment')loadAdjustments();if(b.dataset.page==='movements')loadMovements()});
function table(headers,rows){return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}" class="empty">No data</td></tr>`}</tbody></table></div>`}function badge(v){let c=['IN','TRANSFER_IN','ADJUST_IN','APPROVED','COMPLETED'].includes(v)?'in':['PENDING','PENDING_APPROVAL'].includes(v)?'pending':'out';return `<span class="badge ${c}">${esc(v)}</span>`}
