const masterDefs={
 products:{title:'Product Master',sub:'สินค้า, Barcode, Category, Storage Type',url:'products',fields:[['sku','SKU'],['name','Product Name'],['barcode','Barcode'],['unit','Unit'],['category_code','Category'],['storage_type','Storage Type'],['min_stock','Min Stock','number']],headers:['SKU','Name','Barcode','Unit','Category','Storage','Min','Label','Action'],row:x=>[x.sku,x.name,x.barcode||'-',x.unit,x.category_code||'-',x.storage_type||'-',fmt(x.min_stock),`<button class="mini" onclick="printLabel('${esc(x.sku)}')">Print</button>`,`<button class="mini danger" onclick="deleteMaster('${esc(x.id)}','${esc(x.sku)}')">Delete</button>`]},
 warehouses:{title:'Warehouse Master',sub:'คลังสินค้า',url:'warehouses',fields:[['code','Code'],['name','Name'],['address','Address']],headers:['Code','Name','Address','Action'],row:x=>[x.code,x.name,x.address||'-',masterDeleteButton(x)]},
 zones:{title:'Zone Master',sub:'พื้นที่ภายในคลัง',url:'zones',fields:[['warehouse_code','Warehouse','select','warehouses'],['code','Code'],['name','Name']],headers:['Warehouse','Code','Name','Action'],row:x=>[x.warehouse_code,x.code,x.name,masterDeleteButton(x)]},
 locations:{title:'Location Master',sub:'Rack / Bay / Bin',url:'locations',fields:[['warehouse_code','Warehouse','select','warehouses'],['zone_code','Zone','select','zones'],['code','Code'],['name','Name']],headers:['Warehouse','Zone','Code','Name','Action'],row:x=>[x.warehouse_code,x.zone_code,x.code,x.name||'-',masterDeleteButton(x)]},
 units:{title:'Unit Master',sub:'หน่วยนับ',url:'units',fields:[['code','Code'],['name','Name']],headers:['Code','Name','Action'],row:x=>[x.code,x.name,masterDeleteButton(x)]},
 categories:{title:'Category Master',sub:'หมวดสินค้า',url:'categories',fields:[['code','Code'],['name','Name']],headers:['Code','Name','Action'],row:x=>[x.code,x.name,masterDeleteButton(x)]},
 storageTypes:{title:'Storage Type',sub:'ประเภทการจัดเก็บ',url:'storage-types',fields:[['code','Code'],['name','Name']],headers:['Code','Name','Action'],row:x=>[x.code,x.name,masterDeleteButton(x)]},
 reasonCodes:{title:'Reason Code',sub:'เหตุผล Movement / Adjustment',url:'reason-codes',fields:[['code','Code'],['name','Name'],['movement_type','Movement Type']],headers:['Code','Name','Type','Action'],row:x=>[x.code,x.name,x.movement_type,masterDeleteButton(x)]},
 employees:{title:'User / Employee',sub:'User + Role Permission',url:'employees',fields:[['code','Code'],['name','Name'],['username','Username'],['password','Password'],['role','Role'],['email','Email']],headers:['Code','Name','Username','Role','Email','Active','Action'],row:x=>[x.code,x.name,x.username,x.role,x.email||'-',x.active?'Yes':'No',masterDeleteButton(x)]},
 suppliers:{title:'Supplier Master',sub:'ผู้ขาย',url:'suppliers',fields:[['code','Code'],['name','Name'],['phone','Phone'],['email','Email']],headers:['Code','Name','Phone','Email','Action'],row:x=>[x.code,x.name,x.phone||'-',x.email||'-',masterDeleteButton(x)]},
 customers:{title:'Customer Master',sub:'ลูกค้า',url:'customers',fields:[['code','Code'],['name','Name'],['phone','Phone'],['email','Email']],headers:['Code','Name','Phone','Email','Action'],row:x=>[x.code,x.name,x.phone||'-',x.email||'-',masterDeleteButton(x)]}
};

document.querySelectorAll('.master-card').forEach(b=>b.onclick=()=>{document.querySelectorAll('.master-card').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeMaster=b.dataset.master;loadMaster()});
async function loadMaster(){const d=masterDefs[activeMaster];$('masterTitle').textContent=d.title;$('masterSub').textContent=d.sub;$('exportProductBtn').style.display=activeMaster==='products'?'':'none';$('importProductBtn').style.display=activeMaster==='products'?'':'none';try{const rows=await api('/api/'+d.url);$('masterTable').innerHTML=table(d.headers,rows.map(x=>`<tr>${d.row(x).map(v=>`<td>${typeof v==='string'&&v.startsWith('<button')?v:esc(v)}</td>`).join('')}</tr>`))}catch(e){$('masterTable').innerHTML=`<div class="empty">${esc(e.message)}</div>`}}
function masterDeleteButton(row){return `<button class="mini danger" onclick="deleteMaster('${esc(row.id)}','${esc(row.code||row.sku||row.username||'record')}')">Delete</button>`}
function selectOptions(rows,label){return rows.map(x=>`<option value="${esc(x.code)}">${esc(x.code)} - ${esc(x.name||label||'')}</option>`).join('')}
function renderMasterSelect(name,label,source,masters){const dependent=source==='zones';const options=dependent?'':selectOptions(masters[source]||[],label);return `<label>${label}<select id="mf_${name}" data-source="${source}" required${dependent?' disabled':''}><option value="">Select ${label}</option>${options}</select></label>`}
async function openMasterForm(){const d=masterDefs[activeMaster];$('masterFormTitle').textContent='Add '+d.title;let masters={};if(!document.getElementById('masterSelectStyles')){const style=document.createElement('style');style.id='masterSelectStyles';style.textContent='.modal-card select{width:100%;margin-top:6px;padding:12px;border:1px solid #d0d5dd;border-radius:8px;background:#fff;color:#182230;font:inherit;line-height:1.4;cursor:pointer}.modal-card select:focus{outline:2px solid #84adff;outline-offset:1px}.modal-card select:disabled{background:#f2f4f7;color:#98a2b3;cursor:not-allowed}.modal-card input:invalid,.modal-card select:invalid{border-color:#f04438}';document.head.appendChild(style)}if(activeMaster==='zones'||activeMaster==='locations'){const warehouses=await api('/api/warehouses');masters.warehouses=warehouses}if(activeMaster==='locations')masters.zones=await api('/api/zones');$('masterFields').innerHTML=d.fields.map(([n,l,t,source])=>t==='select'?renderMasterSelect(n,l,source,masters):`<label>${l}<input id="mf_${n}" type="${t||'text'}" required ${t==='number'?'step="0.01"':''}></label>`).join('');if(activeMaster==='zones')$('mf_warehouse_code').onchange=()=>{};if(activeMaster==='locations')$('mf_warehouse_code').onchange=()=>{const zone=$('mf_zone_code');const warehouse=$('mf_warehouse_code').value;zone.value='';zone.innerHTML='<option value="">Select Zone</option>';if(!warehouse){zone.disabled=true;return}zone.innerHTML+=selectOptions(masters.zones.filter(x=>x.warehouse_code===warehouse),'Zone');zone.disabled=false};$('masterForm').classList.remove('hidden')}
function closeMasterForm(){$('masterForm').classList.add('hidden')}
async function saveMaster(){const d=masterDefs[activeMaster],body={};for(const [name,,type] of d.fields){const field=$('mf_'+name);if(!field.value.trim()){field.reportValidity();return}body[name]=type==='number'?Number(field.value):field.value.trim()}try{await api('/api/'+d.url,{method:'POST',body:JSON.stringify(body)});closeMasterForm();loadMaster()}catch(e){alert(e.message)}}
async function deleteMaster(id,code){if(!id||!confirm(`Delete ${code}?`))return;try{await api('/api/'+masterDefs[activeMaster].url+'/'+encodeURIComponent(id),{method:'DELETE'});loadMaster()}catch(e){alert(e.message)}}
